name = input("Enter your name: ")
IDno = input("Enter your ID number: ")
Department = input("enter Your Department: ")
Year = int(input("Enter year: "))
university = input("Enter your uiversity: ")
Phone  = int(input("Enter your phone number: "))
# Print the student information
print("+----------------------------------+")
print("|      AKIBA STUDENT CARD          |")
print("+----------------------------------+")
print(f"| Name: {name:<30}|")
print(f"| ID Number: {IDno:<23}|")
print(f"| Department: {Department:<22}|")
print(f"| Year: {Year:<27}|")
print(f"| University: {university:<22}|")
print(f"| Phone: {Phone:<27}|")
print("+----------------------------------+")